services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "49152:49152"
    networks:
      - shared-network

  vault-service:
    build: ./vault-service
    ports:
      - "49153:49153"
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
