package vault.manager.vaultService.server.grpc

import vault.manager.vaultService.server.ValidationServiceGrpcKt
import vault.manager.vaultService.server.ValidationServiceOuterClass
import vault.manager.vaultService.server.validateResponse

typealias AutogeneratedValidationGrpcService = ValidationServiceGrpcKt.ValidationServiceCoroutineImplBase
typealias ValidateRequest = ValidationServiceOuterClass.ValidateRequest
typealias ValidateResponse = ValidationServiceOuterClass.ValidateResponse

object ValidationGrpcService : AutogeneratedValidationGrpcService() {
    override suspend fun validate(request: ValidateRequest): ValidateResponse =
        validateResponse {
            defects.addAll(emptyList())
        }
}
