package vault.manager.vaultService.server

typealias AutogeneratedValidationGrpcService = ValidationServiceGrpcKt.ValidationServiceCoroutineImplBase
typealias ValidateRequest = ValidationServiceOuterClass.ValidateRequest
typealias ValidateResponse = ValidationServiceOuterClass.ValidateResponse

object ValidationGrpcService : AutogeneratedValidationGrpcService() {
    override suspend fun validate(request: ValidateRequest): ValidateResponse =
        validateResponse {
            defects.addAll(emptyList())
        }
}
