package vault.manager.vaultService.server

typealias AutogeneratedValidationGrpcService = ValidationServiceGrpcKt.ValidationServiceCoroutineImplBase
typealias ValidateRequest = ValidationServiceOuterClass.ValidateRequest
typealias ValidateResponse = ValidationServiceOuterClass.ValidateResponse

class ValidationGrpcService : AutogeneratedValidationGrpcService() {
    override suspend fun validate(request: ValidateRequest): ValidateResponse {
        return validateResponse {
            defects.addAll(emptyList())
        }
    }
}
