[versions]
idea-ext = "1.1.8"
junit = "5.10.3"
kotlin = "2.0.0"

[libraries]
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }

[bundles]
junit = ["junit-jupiter-engine", "junit-jupiter-api"]

[plugins]
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea-ext" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
